WA-28
Hommasoft/wappuapp-backend pull request #1
Opened 2017-11-08 12:12 UTC by Jeva92

Backend functionality for login and register. 
Middleware for requireAuth might not be fully working and for this, another PR will be made later.

2017-11-08 13:06 UTC, mikael-lagerbom requested changes

2017-11-08 13:06 UTC, mikael-lagerbom commented on src/http/login-http.js
> +  return knex.raw(sqlString)
Tän sais ihan kivasti näinkin
`return knex('admin').select('id').where('username', username);`
Ei tarvis näitä rumia raaka-SQL muuttujia

2017-11-08 13:06 UTC, mikael-lagerbom commented on src/http/login-http.js
> +  return jwt.encode({ sub: id, iat: timestamp }, "SECRET");
Secret vaikka .enviin, jos ei siellä jo ole, ja ladataan sitten sieltä

2017-11-08 13:06 UTC, mikael-lagerbom commented on src/http/login-http.js
> +      return knex.raw(sqlString)
Samoin kun tuossa ylempänä, 
`return knex('admin').insert({ username: username, email: email, password: password });`

2017-11-08 13:06 UTC, mikael-lagerbom commented on src/http/login-http.js
> +          const id = result.rows[0].id;
Jos haluat vaan ensimmäisen tuloksen querystä, voi käyttää 
`return knex('admin').select('id').where('username', username).first();`

2017-11-08 13:06 UTC, Mikhepls commented on src/http/login-http.js
> +      return throwStatus(422, 'Username exists');
Olisi myös varmaan hyvä tarkistaa ettei sähköposti ole jo käytössä?

2017-11-08 13:06 UTC, Mikhepls commented on src/util/passport.js
> +  (SELECT admin.username FROM admin WHERE admin.username = '${username}')
Samat setit kun tuolla ylempänä

2017-11-08 13:06 UTC, Mikhepls commented on src/util/passport.js
> +  (SELECT admin.id FROM admin WHERE admin.id = '${payload.sub}')
Sen lisäksi että tarkistetaan löytyykö pätevällä id:llä käyttäjä, vois olla hyvä kattoa että siitä issued-at ajasta ei oo kulunu ihan kauhean kauaa. Joku parin päivän expiration vois olla ihan ok?

2017-11-08 13:09 UTC, Jeva92 commented on src/http/login-http.js
> +  return jwt.encode({ sub: id, iat: timestamp }, "SECRET");
tuo oli lähinnä placeholder, ajattelin että jokin yhteinen sävel tällaisille arvoille olisi hyvä sopia. .env kuulostaa hyvältä

2017-11-08 13:09 UTC, Jeva92 commented on src/http/login-http.js
> +  return knex.raw(sqlString)
will do

2017-11-08 13:09 UTC, Jeva92 commented on src/http/login-http.js
> +      return knex.raw(sqlString)
will do

2017-11-08 13:09 UTC, Jeva92 commented on src/http/login-http.js
> +          const id = result.rows[0].id;
will do

2017-11-08 13:10 UTC, Jeva92 commented on src/http/login-http.js
> +      return throwStatus(422, 'Username exists');
voisi

2017-11-08 13:10 UTC, Jeva92 commented on src/util/passport.js
> +  (SELECT admin.username FROM admin WHERE admin.username = '${username}')
will do

2017-11-08 13:10 UTC, Jeva92 commented on src/util/passport.js
> +  (SELECT admin.id FROM admin WHERE admin.id = '${payload.sub}')
voisi

2017-11-11 12:06 UTC, Jeva92 commented
Kaikki paitsi Secretin siirtäminen .env tiedostoon tehty.

2017-11-11 14:03 UTC, mikael-lagerbom approved these changes
Jos Anssin testailut menee läpi ni voi mergee

2017-11-11 14:03 UTC, Mikhepls commented on migrations/20171111134906_add_admin_table.js
> +    table.integer('power').notNullable().defaultTo(0);
Tää on aika kyseenalainen tapa hoitaa oikeuksia mut kelvannee tässä kohtaa

2017-11-11 14:03 UTC, Mikhepls commented on src/util/passport.js
> +    const timeSpent = nowTime.diff(startTime, 'hours')
Tää on vähän funky tapa selvittää expiration hetki, tai ainakin muuttujanimet on vähän hassuja. Vois olla nätimpi ottaa toi iat+expiration aika ja verrata nykyhetkeen, et jos sen stamppi on nykyhetkeä pienempi ni fail. Mut kelpaa.

2017-11-13 20:22 UTC, Aivoapina approved these changes

2017-11-14 09:14 UTC, merged